version: '3.3'

services:
  api:
    build:
      context: "."
      dockerfile: "Dockerfile.local"
    restart: always
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - mysql-network
  db:
    build: 
      context: "./schema"
      dockerfile: "Dockerfile.db"
    restart: always
    environment:
      MYSQL_DATABASE: "auxify"
      MYSQL_ROOT_PASSWORD: "example"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network


volumes:
  mysql-data:
networks:
  mysql-network: